# -*- coding: utf-8 -*-
"""DilshanGPT_v4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18O90XzilKDAxRLFBOptEfQujRomv4sz-
"""

pip install -q -U google-genai

pip install langchain langchain-community langchain_text_splitters langchain_openai langchain_chroma

pip install -U langchain-google-genai

from langchain_community.document_loaders import TextLoader, DirectoryLoader  #help to read files
from langchain_text_splitters import CharacterTextSplitter    #for create chunks
from langchain_google_genai import GoogleGenerativeAIEmbeddings #for embeddings
from langchain_chroma import Chroma #stores the vectors

import os
from google.colab import userdata

from google import genai

os.environ["GOOGLE_API_KEY"] = userdata.get('Google_API_Key')

def load_documents(docs_path="docs"):
  """Load all .txt files in the directory."""

  loader = DirectoryLoader(
      docs_path,
      glob="*.txt",
      loader_cls=TextLoader
  )

  documents = loader.load()

  # show first 2 documents
  # for i,doc in enumerate(documents[:2]):
  #   print(f"\n Document : {i + 1}")
  #   print(f"Meta Data {doc.metadata}")
  #   print(f"Content {doc.page_content}")

  return documents

def split_documents(documents,chunk_size=100,chunk_overlap=0):
  """Split documents into chunks."""

  text_splitter = CharacterTextSplitter(
      chunk_size = chunk_size,
      chunk_overlap = chunk_overlap
  )

  chunks = text_splitter.split_documents(documents)

  #print chunks
  # for i,chunk in enumerate(chunks[:2]):
  #   print(f"\n Chunk : {i + 1}")
  #   print(chunk)

  return chunks

def create_vector_store(chunks , precist_directory = "db/chroma_db"):
  """Create a vector store from chunks."""
  print("Creating Embedding and Storing in Chroma DB")

  embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

  print("Creating vector store")
  vector_store = Chroma.from_documents(
      chunks,
      embedding_model,
      persist_directory=precist_directory,
      collection_metadata={"hnsw:space": "cosine"}
  )

  print(f"\nFinished Creting Persisting vector store, Stored at {precist_directory}")

  return vector_store

def retreve_related_chunks(query, vector_store):
  """Retreve related chunks from the vector store."""

  retrever = vectorStore.as_retriever(search_kwargs={"k": 2})

  relevent_docs = retrever.invoke(query)

  #print relevent docs
  for i,doc in enumerate(relevent_docs):
    print(f"\n Document : {i + 1}")
    print(f"Content {doc.page_content}")

  return relevent_docs

def generate_answer(query, relevent_docs):
  """Generate answer from the relevent chunks."""
  chunks = ""
  for i,doc in enumerate(relevent_docs):
    chunks += (f'\nDocument {i}:  {doc.page_content}')
  # print(chunks)

  prompt = f"""Based on Following Documents please answer the question '{query}'

  Documents :{chunks}

  Please provide a clear helpful answer using only the infromation from these documents.If you can't find the answer in the document say 'I dont have ennough information to answer that question based on provided documents'"""

  # print(prompt)

  client = genai.Client()

  response = client.models.generate_content(
      model="gemini-3-flash-preview",
      contents=prompt
  )

  return response.text

print("Main Function")

#Load The Files
documents = load_documents(docs_path="docs")

#Chunk The Documnets
chunks = split_documents(documents)

#Create Vector store
vectorStore = create_vector_store(chunks)

#Retrive Related chunks
query = "Dilshan aims to become ?"
relevent_docs = retreve_related_chunks(query, vectorStore)

#Generate Sutable Answer using LLM
generated_answer = generate_answer(query, relevent_docs)
print(generated_answer)