# -*- coding: utf-8 -*-
"""DilshanGPT_v4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18O90XzilKDAxRLFBOptEfQujRomv4sz-
"""

pip install -q -U google-genai

pip install langchain langchain-community langchain_text_splitters langchain_openai langchain_chroma

pip install -U langchain-google-genai


from langchain_community.document_loaders import TextLoader, DirectoryLoader  #help to read files
from langchain_text_splitters import CharacterTextSplitter    #for create chunks
from langchain_google_genai import GoogleGenerativeAIEmbeddings #for embeddings
from langchain_chroma import Chroma #stores the vectors

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('Google_API_Key')

def load_documents(docs_path="docs"):
  """Load all .txt files in the directory."""

  loader = DirectoryLoader(
      docs_path,
      glob="*.txt",
      loader_cls=TextLoader
  )

  documents = loader.load()

  # show first 2 documents
  # for i,doc in enumerate(documents[:2]):
  #   print(f"\n Document : {i + 1}")
  #   print(f"Meta Data {doc.metadata}")
  #   print(f"Content {doc.page_content}")

  return documents

def split_documents(documents,chunk_size=100,chunk_overlap=0):
  """Split documents into chunks."""

  text_splitter = CharacterTextSplitter(
      chunk_size = chunk_size,
      chunk_overlap = chunk_overlap
  )

  chunks = text_splitter.split_documents(documents)

  #print chunks
  # for i,chunk in enumerate(chunks[:2]):
  #   print(f"\n Chunk : {i + 1}")
  #   print(chunk)

  return chunks

def create_vector_store(chunks , precist_directory = "db/chroma_db"):
  """Create a vector store from chunks."""
  print("Creating Embedding and Storing in Chroma DB")

  embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

  print("Creating vector store")
  vector_store = Chroma.from_documents(
      chunks,
      embedding_model,
      persist_directory=precist_directory,
      collection_metadata={"hnsw:space": "cosine"}
  )

  print(f"\nFinished Creting Persisting vector store, Stored at {precist_directory}")

  return vector_store

print("Main Function")

#Load The Files
documents = load_documents(docs_path="docs")

#Chunk The Documnets
chunks = split_documents(documents)

#Create Vector store
vectorStore = create_vector_store(chunks)