 # -*- coding: utf-8 -*-
"""DilshanGPT_v4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18O90XzilKDAxRLFBOptEfQujRomv4sz-
"""

#pip install -q -U google-genai

#pip install langchain langchain-community langchain_text_splitters langchain_openai langchain_chroma

#pip install langchain-classic

#pip install -U langchain-google-genai

#pip install rank_bm25

#!apt-get install poppler-utils tesseract-ocr libmagic-dev

#pip install "unstructured[all-docs]"

from langchain_community.document_loaders import TextLoader, DirectoryLoader  #help to read files
from langchain_text_splitters import CharacterTextSplitter    #for create chunks
from langchain_google_genai import GoogleGenerativeAIEmbeddings #for embeddings
from langchain_chroma import Chroma #stores the vectors

from langchain_community.retrievers import BM25Retriever

import pickle
import os

from google import genai

from unstructured.partition.pdf import partition_pdf
from unstructured.chunking.title import chunk_by_title

os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_API_KEY")

class Post:
    """Terminal Color Helper"""
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    SUCCESS = '\033[92m'  # Green
    WARNING = '\033[93m'  # Yellow
    FAIL = '\033[91m'     # Red
    ENDC = '\033[0m'      # Resets color back to normal
    BOLD = '\033[1m'


def load_documents(docs_path="docs"):
  """Load all .txt files in the directory."""

  loader = DirectoryLoader(
      docs_path,
      glob="*.txt",
      loader_cls=TextLoader
  )

  documents = loader.load()

  # show first 2 documents
  # for i,doc in enumerate(documents[:2]):
  #   print(f"\n Document : {i + 1}")
  #   print(f"Meta Data {doc.metadata}")
  #   print(f"Content {doc.page_content}")

  return documents

def split_documents(documents,chunk_size=300,chunk_overlap=0):
  """Split documents into chunks."""

  text_splitter = CharacterTextSplitter(
      chunk_size = chunk_size,
      chunk_overlap = chunk_overlap
  )

  chunks = text_splitter.split_documents(documents)

  #print chunks
  # for i,chunk in enumerate(chunks[:2]):
  #   print(f"\n Chunk : {i + 1}")
  #   print(chunk)

  return chunks

def partition_pdf_doc(file_path: str):
  """Extract Elements From the PDF.using unstructured libarary"""
  elements = partition_pdf(
      file_path,
      strategy="hi_res",
      extract_image_block_types=["Image"],
      extract_image_block_to_payload=True,  # store image as Base64
      infer_table_structure=True
      )
  print(f"extracted {len(elements)} elements")
  return elements

#file_path = './docs/CYBER_SECURITY.pdf'
#elements = partition_pdf_doc(file_path)

#elements
#elements[10].to_dict()['text']

def create_chunks_by_title(elements):
  """Create Smart chunks From the extracted elements of the PDF."""
  pdf_chunks = chunk_by_title(
      elements,   #parsed pdf elements
      max_characters=3000,   # hard-limt : nerver exceed 3000
      new_after_n_chars=2400, # try to start creting a new chunk after 2400
      combine_text_under_n_chars=500 # merge tiny chunks under 500
  )

  print(f"{Post.SUCCESS}Smart chunk Created : {len(pdf_chunks)}...{Post.ENDC}")
  return pdf_chunks

#pdf_chunks = create_chunks_by_title(elements)

#pdf_chunks
#pdf_chunks[1].to_dict()
#pdf_chunks[2].metadata.orig_elements   contain images
#pdf_chunks[2].metadata.orig_elements[4]   image class
#pdf_chunks[2].metadata.orig_elements[4].to_dict()  image contain
#pdf_chunks[2].metadata.orig_elements[4].to_dict()['metadata']['image_base64']

#test_chunk = pdf_chunks[2]

#test_chunk.to_dict()

def seperate_content_types(pdf_chunk):
  """Seperate the content types from the chunk."""
  content_data = {
      'text' : pdf_chunk.text,
      'tables' : [],
      'images' : [],
      'types'  : ['text']
  }

  #print(f"{hasattr(chunk,'metadata')}")
  #print(f"{hasattr(chunk.metadata,'orig_elements')}")

  if hasattr(pdf_chunk,'metadata') and hasattr(pdf_chunk.metadata,'orig_elements'):
    #print("metadata found, and origelements under metadata found")
    for element in pdf_chunk.metadata.orig_elements:
      element_type = type(element).__name__
      print(f"Element Type Found from seperate content type() : {element_type}")

      if element_type == 'Table':
        content_data['types'].append('table')
        table_html = getattr(element.meatadata,'text_as_html',element.text)
        content_data['tables'].append(table_html)

      elif element_type == 'Image':
        if hasattr(element,'metadata') and hasattr(element.metadata,'image_base64'):
          content_data['types'].append('image')
          content_data['images'].append(element.metadata.image_base64)


  content_data['types'] = list(set(content_data['types']))
  return content_data

# content_data = seperate_content_types(test_chunk)

# print(f"\nContent Data after analyze : {content_data}")
# print(f"\nContent image {content_data['images']}")
# print(f"\nTypes {content_data['types']}")

#content_data

from typing import List
from google import genai
def create_ai_enhansed_summary(text: str,tables: List[str],images: List[str]) -> str:
  """Create AI enhanced summary of the text."""
  prompt_text = f""" You are creating a searchable discryption for document content retrieval.

  CONTENT TO ANALYZE:
  TEXT CONTENT : {text}

  """

  if tables:
    prompt_text += "TABLES :\n"
    for i,table in enumerate(tables):
      prompt_text += f"\nTable {i + 1} :\n {table}\n"

    prompt_text += """
       YOUR TASK:
       generate a comprehensive, searchable discryption that covers:

       1. Key Facts,numbers and data points from text and tabel
       2. Main topics and concepts discussed
       3. Questions this content could answer
       4. Alternative search terms users might use

       make it detailed and searchable - prioritize fidability over brivity

       SEARCHABLE DISCRIPTION :
      """

  # Correct way to construct message_content for multimodal input using genai.types.Part
  message_content = [genai.types.Part(text=prompt_text)]

  for image_base64 in images:
    message_content.append(
        genai.types.Part(
            inline_data=genai.types.Blob(
                mime_type='image/jpeg',
                data=image_base64
            )
        )
    )

  #print(f"Message Content : {message_content}" )

  #Send to LLM And Get Summerized Text
  client = genai.Client()
  response = client.models.generate_content(
      model="gemini-3-flash-preview",
      contents=message_content
  )

  return response.text

# enhansed_pdf_chunk = create_ai_enhansed_summary(
#             content_data['text'],
#             content_data['tables'],
#             content_data['images']
#         )
# print(f"Ai summery creted suvessfully")
# print(f"Enhansed pdf chunk {enhansed_pdf_chunk}")

from IPython.core.display import json
from langchain_core.documents import Document
def summerise_chunks(pdf_chunks):
  """Summerise the chunks that contain tables,images to text"""

  lanchain_documnets = []
  total_chunks = len(pdf_chunks)

  for i,pdf_chunk in enumerate(pdf_chunks):
    print(f"Summerising Chunk {i + 1} of {total_chunks}")

    #Analyse chunk contains
    content_data = seperate_content_types(pdf_chunk)
    #print(f"\nContent Data after analyze : {content_data}")

    print(f"\nTable Found : {len(content_data['tables'])}")
    print(f"\nImages Found : {len(content_data['images'])}")

    #Create AI enhansed summmery if contian Table/Images
    if 'table' in content_data['types'] or 'image' in content_data['types']:
      print(f"\n Summerising the pdf chunk")

      try:
        enhansed_pdf_chunk = create_ai_enhansed_summary(
            content_data['text'],
            content_data['tables'],
            content_data['images']
        )
        print(f"{Post.SUCCESS}Ai summery creted suvessfully{Post.ENDC}")
        print(f"Enhansed pdf chunk {enhansed_pdf_chunk}")

      except:
        print(f"{Post.WARNING}Ai summery creted failed{Post.ENDC}")
        enhansed_pdf_chunk = content_data['text']

    else:
      print(f"\n Using Raw Text no image/tables")
      enhansed_pdf_chunk = content_data['text']

    #Create Langchain Document with rich metadata
    doc = Document(
        page_content=enhansed_pdf_chunk,
        metadata={
            "original_content" : json.dumps({
                "raw_text" : content_data['text'],
                "tables_html" : content_data['tables'],
                "images_base64" : content_data['images']
            })
        }
    )

    lanchain_documnets.append(doc)

  print(f"{Post.SUCCESS}Total Chunks Summerised : {len(lanchain_documnets)}...{Post.ENDC}")
  return lanchain_documnets

#pdf_chunks_after_summarise = summerise_chunks(pdf_chunks)

#chunks[0].page_content
#chunks[0].metadata

def create_vector_store(chunks , precist_directory = "db/chroma_db"):
  """Create a vector store from chunks."""
  print("Creating Embedding and Storing in Chroma DB")

  embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

  print("Creating vector store")
  vector_store = Chroma.from_documents(
      chunks,
      embedding_model,
      persist_directory=precist_directory,
      collection_metadata={"hnsw:space": "cosine"}
  )

  print(f"\n{Post.SUCCESS}Finished Creting Persisting vector store, Stored at {precist_directory} ... {Post.ENDC}")

  return vector_store

#vectorStore = create_vector_store(chunks)

#query = "What are the types of mobility"

def retreve_related_chunks(query, vector_store):
  """Retreve related chunks from the vector store."""

  vector_retrever = vector_store.as_retriever(search_kwargs={"k": 3})

  relevent_docs = vector_retrever.invoke(query)

  print(f"{Post.SUCCESS}Documents Found From VectorDB/Similerty : {len(relevent_docs)}...{Post.ENDC}")
  #print relevent docs
  # for i,doc in enumerate(relevent_docs):
  #   print(f"\n Document From Vector DB: {i + 1}")
  #   print(f"Content {doc.page_content}")

  return relevent_docs

#test = retreve_related_chunks(query,vectorStore)
#print(test)

def keyword_search(query,chunks):
  """Retreve related chunks from the vector store."""
  bm25_retriever = BM25Retriever.from_documents(chunks)
  bm25_retriever.k = 2

  test_query = query
  keyword_docs  = bm25_retriever.invoke(test_query)

  print(f"{Post.SUCCESS}Documents Found From KeyWord : {len(keyword_docs)}...{Post.ENDC}")

  # for doc in keyword_docs[:2]:
  #   print(f"\n\n Docs Found From Keyword {doc.page_content}")
  return keyword_docs

def hybrid_retrieve(query ,vector_store, chunks, k=5):
    docs_vec = retreve_related_chunks(query, vector_store)
    docs_bm25 = keyword_search(query, chunks)

    combined = docs_vec + docs_bm25

    # Remove duplicates
    seen = set()
    unique_docs = []

    for doc in combined:
        content = doc.page_content
        if content not in seen:
            seen.add(content)
            unique_docs.append(doc)

    #print(f'\n\n Docs From hybrid Search {unique_docs}')
    return unique_docs[:k]

def generate_answer(query, relevent_docs):
  """Generate answer from the relevent chunks."""
  chunks = ""
  for i,doc in enumerate(relevent_docs):
    chunks += (f'\nDocument {i}:  {doc.page_content}')
  # print(chunks)

  prompt = f"""Based on Following Documents please answer the question '{query}'

  Documents :{chunks}

  Please provide a clear helpful answer using only the infromation from these documents.If you can't find the answer in the document say 'I dont have ennough information to answer that question based on provided documents'"""

  # print(prompt)

  client = genai.Client()

  response = client.models.generate_content(
      model="gemini-3-flash-preview",
      contents=prompt
  )

  return response.text

# Store Coversations
#chat_history = []

#print(chat_history)

def generate_proper_question(query,chat_history):
  """Generate conversation with the LLM."""
  print(f"You Asked {query}")

  if chat_history:
    prompt = f"""Given The Chat History and a follow up question, Rewrite the question to be a standalone searchable question. Just return the rewritten question. Don't answer anything else.
    Chat History : {chat_history}

    follow up question : {query}

    """
    client = genai.Client()
    response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents=prompt
    )
    print(f"{Post.OKBLUE}\n\nRewritten Question : {response.text}..{Post.ENDC}")
    return response.text
  else:
    return query

def create_chunks():

    #Load The text Files
    documents = load_documents(docs_path="docs")
    #Chunk The Text Documents
    text_chunks = split_documents(documents)
    
    #Chunk The Pdf Documents
    file_path = './docs/CYBER_SECURITY.pdf'
    elements = partition_pdf_doc(file_path)
    pdf_chunks = create_chunks_by_title(elements)
    pdf_chunks_summarized = summerise_chunks(pdf_chunks)

    #Combine All chunks
    chunks = text_chunks + pdf_chunks_summarized

    return chunks

def save_chunks(chunks, filename="chunks_data.pkl"):
    """Saves the processed Langchain documents to a local file."""
    with open(filename, 'wb') as f:
        pickle.dump(chunks, f)
    print(f"{Post.SUCCESS}Successfully saved {len(chunks)} chunks to {filename} ... {Post.ENDC}")


def load_saved_chunks(filename="chunks_data.pkl"):
    """Loads chunks from local storage for the BM25 retriever."""
    if os.path.exists(filename):
        with open(filename, 'rb') as f:
            chunks = pickle.load(f)
        print(f"{Post.SUCCESS}Loaded {len(chunks)} chunks from local storage.{Post.ENDC}")
        return chunks
    else:
        print(f"{Post.FAIL}No saved chunks found! You need to run the ingestion script first.{Post.ENDC}")
        return None


def build_and_save_db():
    
    #Create Chunks
    print(f"Creating Chunks...")
    chunks = create_chunks()

    #Save Chunks on Local Storage
    save_chunks(chunks)

    #Create Vector store
    print(f"Creting Vector Store...")
    vectorStore = create_vector_store(chunks)

    print(f"{Post.SUCCESS}Database built and saved locally!{Post.ENDC}")



def get_existing_vector_store():
    embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")
    
    # Load the database from the folder
    vector_store = Chroma(
        persist_directory="./db/chroma_db", 
        embedding_function=embedding_model,
        collection_metadata={"hnsw:space": "cosine"}
    )
    return vector_store

# def start_chat():
    # Load the DB From the local Storage
    ##vectorStore = get_existing_vector_store()
    # Load the chunks From the local Storage
    ##chunks = load_saved_chunks()


    #print("Chatbot Ready! Type exit to quit.")
    # while True:
    #     query = input("User: ")
    #     if query.lower() == "exit": break
        
        # Now use the 'vectorStore' we loaded above 
        # (Make sure your hybrid_retrieve function accepts vectorStore as an argument)
        # proper_query = generate_proper_question(query,chat_history)
        # prop_que_to_history = f"User asked : {proper_query}"
        # chat_history.append(prop_que_to_history)
        # docs = hybrid_retrieve(proper_query, vectorStore , chunks) # Pass it here!
        
        # response = generate_answer(query, docs)
        # gen_ans_to_history = f"DilshanGPT response: {response}"
        # chat_history.append(gen_ans_to_history)
        # print(f"DilshanGPT: {response}")



# if __name__ == "__main__":
#     db_path = "./db/chroma_db"
    
#     if not os.path.exists(db_path):
#         print("Database not found. Building now...")
#         build_and_save_db()
#     else:
#         print("Database found! Loading chat...")
        
#     start_chat()





